export const Remedies = [
  {
    disease: "Eczema",
    remedies: [
      'Moisturize your skin often with "Dermive Sensitive" moisturizer.',
      "Avoid sudden changes in temperature or humidity.",
      "Try not to sweat or get too hot.",
      "Avoid scratchy materials such as wool.",
      "Don’t use harsh soaps, detergents, or solvents.",
      'Use "White Lux or Dove".',
      "Pay attention to foods that might trigger symptoms and try to avoid them.",
      'Use anti-itching tablet "Softin 10g" if you experience itching (1 tab before going to bed).',
      "Visit the nearest dermatologist for further proper treatment.",
    ],
  },
  {
    disease: "Actinic keratosis and Intrapithelial carcinoma",
    remedies: [
      "Avoid direct exposure to sunlight.",
      "Do not touch effected area directly.",
      "Avoid using anti-bacterial soaps.",
      'Wash infected area with "White Lux or Dove".',
      'Use "U-Veil Forte" sunblock before going out.',
      'Use anti-itching tablet "Softin 10g" if you experience itching (1 tab before going to bed).',
      'Use "Dermive Sensitive" moisturizer.',
      "Visit the nearest dermatologist for further proper treatment.",
    ],
  },
  {
    disease: "Acne",
    remedies: [
      "Keep your skin clean.",
      "Gently wash your face up to twice daily and after sweating.",
      "Keep infected area dry and do not let it get oily.",
      'Use "White Lux or Dove".',
      "Avoid products that can irritate your skin, including astringents, toners, and exfoliants. These products can dry your skin and make acne appear worse.",
      "Touching your face throughout the day can cause acne to flare and can increase your risk for scarring and dark spots.",
      "Avoid sunlight because tanning damages your skin and can worsen acne.",
      'Use "U-Veil Forte" sunblock before going out.',
      'Use anti-itching tablet "Softin 10g" if you experience itching (1 tab before going to bed).',
      "Visit the nearest dermatologist for further proper treatment.",
    ],
  },
  {
    disease: "Vascular Lesion",
    remedies: [
      "Avoid direct exposure to sunlight.",
      "Do not touch effected area directly.",
      "Avoid using anti-bacterial soaps.",
      'Wash infected area with "White Lux or Dove".',
      'Use "U-Veil Forte" sunblock before going out.',
      'Use anti-itching tablet "Softin 10g" if you experience itching (1 tab before going to bed).',
      'Use "Dermive Sensitive" moisturizer.',
      "Visit the nearest dermatologist for further proper treatment.",
    ],
  },
  {
    disease: "Dermatofibroma",
    remedies: [
      "Avoid direct exposure to sunlight.",
      "Do not touch effected area directly.",
      "Avoid using anti-bacterial soaps.",
      'Wash infected area with "White Lux or Dove".',
      'Use "U-Veil Forte" sunblock before going out.',
      'Use anti-itching tablet "Softin 10g" if you experience itching (1 tab before going to bed).',
      'Use "Dermive Sensitive" moisturizer.',
      "Visit the nearest dermatologist for further proper treatment.",
    ],
  },
  {
    disease: "Melanoma",
    remedies: [
      "Avoid direct exposure to sunlight.",
      "Do not touch effected area directly.",
      "Avoid using anti-bacterial soaps.",
      'Wash infected area with "White Lux or Dove".',
      'Use "U-Veil Forte" sunblock before going out.',
      'Use anti-itching tablet "Softin 10g" if you experience itching (1 tab before going to bed).',
      'Use "Dermive Sensitive" moisturizer.',
      "Visit the nearest dermatologist for further proper treatment.",
    ],
  },
  {
    disease: "Melanocytic Nevi",
    remedies: [
      "Avoid direct exposure to sunlight.",
      "Do not touch effected area directly.",
      "Avoid using anti-bacterial soaps.",
      'Wash infected area with "White Lux or Dove".',
      'Use "U-Veil Forte" sunblock before going out.',
      'Use anti-itching tablet "Softin 10g" if you experience itching (1 tab before going to bed).',
      'Use "Dermive Sensitive" moisturizer.',
      "Visit the nearest dermatologist for further proper treatment.",
    ],
  },
  {
    disease: "Benign Keratosis Lesion",
    remedies: [
      "Avoid direct exposure to sunlight.",
      "Do not touch effected area directly.",
      "Avoid using anti-bacterial soaps.",
      'Wash infected area with "White Lux or Dove".',
      'Use "U-Veil Forte" sunblock before going out.',
      'Use anti-itching tablet "Softin 10g" if you experience itching (1 tab before going to bed).',
      'Use "Dermive Sensitive" moisturizer.',
      "Visit the nearest dermatologist for further proper treatment.",
    ],
  },
  {
    disease: "Basal Cell Carcinoma",
    remedies: [
      "Avoid direct exposure to sunlight.",
      "Do not touch effected area directly.",
      "Avoid using anti-bacterial soaps.",
      'Wash infected area with "White Lux or Dove".',
      'Use "U-Veil Forte" sunblock before going out.',
      'Use anti-itching tablet "Softin 10g" if you experience itching (1 tab before going to bed).',
      'Use "Dermive Sensitive" moisturizer.',
      "Visit the nearest dermatologist for further proper treatment.",
    ],
  },
];
