import React from "react";
import Contact from "../components/Contact";
import Head from "next/head";
const contact = () => {
  return (
    <div>
      <Head>
        <title>DermInspect | Contact Us</title>
        <meta name="DermInspect" content="Generated by create next app" />
        <link rel="icon" href="/Logo.png" />
      </Head>
      <Contact />
    </div>
  );
};

export default contact;
