import Head from "next/head";
import { useRouter } from "next/router";
import MainHome from "../components/Home";
import { useAuthContext } from "../hooks/useAuthContext";
import Login from "../components/Login";
import styles from "../styles/Home.module.css";
export default function Home() {
  const router= useRouter()
  const { user } = useAuthContext()
  return (
    <div className={styles.container}>
      <Head>
        <title>DermInspect</title>
        <meta name="DermInspect" content="Generated by create next app" />
        <link rel="icon" href="/Logo.png" />
      </Head>
      {user ? <MainHome/> : <Login />} 
    </div>
  );
}
